[package]
name = "integration-tests"
version = "0.26.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

license = "Apache-2.0 OR GPL-3.0"
readme = "../README.md"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Subxt integration tests that rely on the Substrate binary"

[features]
default = ["subxt/integration-tests"]

[dev-dependencies]
assert_matches = "1.5.0"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
frame-metadata = "15.0.0"
futures = "0.3.26"
hex = "0.4.3"
regex = "1.5.0"
scale-info = { version = "2.5.0", features = ["bit-vec"] }
sp-core = { git = "https://github.com/tidelabs/substrate", branch = "tidechain", default-features = false  }
sp-keyring = { git = "https://github.com/tidelabs/substrate", branch = "tidechain" }
sp-runtime = { git = "https://github.com/tidelabs/substrate", branch = "tidechain" }
syn = "1.0.0"
subxt = { version = "0.26.0", path = "../../subxt" }
subxt-codegen = { version = "0.26.0", path = "../../codegen" }
test-runtime = { path = "../test-runtime" }
tokio = { version = "1.25", features = ["macros", "time"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
wabt = "0.10.0"
which = "4.4.0"
