[package]
name = "test-runtime"
version = "0.26.0"
edition = "2021"
publish = false

[dependencies]
subxt = { path = "../../subxt" }
sp-runtime = { git = "https://github.com/tidelabs/substrate", branch = "tidechain" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }

[build-dependencies]
subxt = { path = "../../subxt" }
tokio = { version = "1.25", features = ["macros", "rt-multi-thread"] }
which = "4.4.0"
jsonrpsee = { version = "0.16.0", features = ["async-client", "client-ws-transport"] }
