[package]
name = "subxt"
version = "0.26.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = true

license = "Apache-2.0 OR GPL-3.0"
readme = "../README.md"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Submit extrinsics (transactions) to a substrate node via RPC"
keywords = ["parity", "substrate", "blockchain"]

[features]
default = ["jsonrpsee-ws", "substrate-compat"]

# Activate this feature to pull in extra Substrate dependencies which make it
# possible to provide a proper extrinsic Signer implementation (PairSigner).
substrate-compat = [
    "sp-core",
    "sp-runtime"
]

# Activate this to expose functionality only used for integration testing.
# The exposed functionality is subject to breaking changes at any point,
# and should not be relied upon.
integration-tests = []
decoder = ["tidefi-primitives"]

# Jsonrpsee if the default RPC provider used in Subxt. However, it can be
# swapped out for an alternative implementation, and so is optional.
jsonrpsee-ws = ["jsonrpsee/async-client", "jsonrpsee/client-ws-transport"]
jsonrpsee-web = ["jsonrpsee/async-wasm-client", "jsonrpsee/client-web-transport"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
scale-info = "2.0.0"
scale-value = "0.6.0"
scale-bits = "0.3"
scale-decode = "0.4.0"
futures = { version = "0.3.26", default-features = false, features = ["std"] }
hex = "0.4.3"
jsonrpsee = { version = "0.16", optional = true, features = ["jsonrpsee-types"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = { version = "1.0.92", features = ["raw_value"] }
thiserror = "1.0.24"
tracing = "0.1.34"
parking_lot = "0.12.0"
frame-metadata = "15.0.0"
derivative = "2.2.0"

subxt-macro = { version = "0.26.0", path = "../macro" }
subxt-metadata = { version = "0.26.0", path = "../metadata" }

# Provides some deserialization, types like U256/H256 and hashing impls like twox/blake256:
impl-serde = { version = "0.4.0" }
primitive-types = { version = "0.12.0", default-features = false, features = ["codec", "scale-info", "serde"] }
sp-core-hashing = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", default-features = false }

# For ss58 encoding AccountId32 to serialize them properly:
base58 = { version = "0.2.0" }
blake2 = { version = "0.10.4", default-features = false }

# These are only included is "substrate-compat" is enabled.
sp-core = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", default-features = false, optional = true }
sp-runtime = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", optional = true }

tidefi-primitives = { git = "https://github.com/tidelabs/primitives", branch = "substrate-monthly-2023-02", optional = true }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
bitvec = "1"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
scale-info = { version = "2.0.0", features = ["bit-vec"] }
tokio = { version = "1.25", features = ["macros", "time", "rt-multi-thread"] }
sp-core = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", default-features = false }
sp-runtime = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", default-features = false }
sp-keyring = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", default-features = false }
sp-version = { git = "https://github.com/tidelabs/substrate", branch = "tidechain-dev", default-features = false }
